### ISSUE TITLE
Possibly rework camera view using picture entity

### ISSUE THREAD

**Issue by dinki** [dinki/View-Assist#155]
To avoid using Advanced Camera Card dependency we may be able to use picture entity instead.  User EyeVision provided this sample:

```
type: custom:button-card
template:
  - variable_template
  - body_template
styles:
  grid:
    - grid-template-areas: |
        "title status"
        "card card"
    - grid-template-rows: min-content 4fr min-content
    - grid-template-columns: 1fr 1fr
  custom_fields:
    title:
      - align-self: start
      - justify-self: start
      - padding: 1px
    card:
      - align-self: center
      - justify-self: center
      - width: auto
      - height: auto
      - max-width: auto
custom_fields:
  title:
    card:
      type: custom:button-card
      icon: mdi:floor-plan
      tap_action:
        action: navigate
        navigation_path: vloerplan
      styles:
        card:
          - background-color: transparent
          - border-width: 0px
          - width: 100%
          - padding: 0px
        grid:
          - grid-template-areas: "\"i n\""
          - grid-template-columns: min-content min-content
        name:
          - font-size: 6vh
          - color: white
        icon:
          - width: 14vh
          - color: white
  card:
    card:
      type: picture-entity
      title: null
      entity: camera.camera_voordeurbel
      show_state: false
      show_name: true
      camera_view: live
      camera_image: camera.camera_voordeurbel
    card_mod:
      style:
        .: |
          .content {
            transform: scale(1.1);
          }
        ha-icon-button:
          $:
            mwc-icon-button:
              $:
                button: |
                  mwc-ripple {
                    display: none;
                  }
```
