### ISSUE TITLE
Create core automation

### ISSUE THREAD

**Issue by dinki** [dinki/View-Assist#17]
View Assist core custom sentence automations should include the following:

* User spoken command(s)
* Variables set for determining where to route the response
* Determination if device is is audio only or audio and video
* Action portion will use the determination to provide audio only, video only, or audio and video responses.  These can be different
* Action portion should reply with sorry notification if the action portion fails

**Comment by dinki** [comment]
This thread is for discussing and creating a core automation.  @mngarchow modified one of my automations with some great additions.  This will be used as the starting point for this discussion:

```
# Main automation configuration
alias: View Assist - Search Wikipedia
description: Search for a wikipedia article by saying who is or what is
trigger:
  - platform: conversation
    command:
      - who is {name}
      - what is [the] [a] [an] {name}
      - Tell me about [the] {name}
condition: []
action:
  - variables:
      target_satellite_device: |-
        {% for sat in expand('group.assist_satellites') %}
          {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
            {{ sat.entity_id }}
          {% endif %}
        {% endfor %}
      target_display_device: "{{ device_id(state_attr(target_satellite_device, 'display_device')) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
    enabled: true
  - service: rest_command.wiki_how
    response_variable: wiki_response
    enabled: true
    data:
      name: "{{ trigger.slots.name  |regex_replace(find=' ', replace='_') }}"
  - service: python_script.set_state
    data:
      entity_id: "{{ target_satellite_device }}"
      title: Wikipedia Search
  - service: python_script.set_state
    data:
      entity_id: "{{ target_satellite_device }}"
      message_font_size: 3vw
  - choose:
    - conditions:
      - condition: template
        value_template: >-
          {% if wiki_response['content']['thumbnail']['source'] != None %}true{%
          else %}false{% endif %}
      sequence:
        - service: python_script.set_state
          data:
            entity_id: "{{ target_satellite_device }}"
            image: "{{ wiki_response['content']['thumbnail']['source'] }}"
        - service: python_script.set_state
          data:
            entity_id: "{{ target_satellite_device }}"
            message: "{{ wiki_response['content']['extract'] }}"
            enabled: true
        - set_conversation_response: "{{ wiki_response['content']['extract'] }}"
          enabled: true
        - service: browser_mod.navigate
          data:
            path: /dashboard-viewassist/infopic
          target:
            device_id: "{{target_display_device}}" 
    - conditions:
      - condition: template
        value_template: >-
          {% if wiki_response['status'] != 404 %}true{%
          else %}false{% endif %}      
      sequence:
        - service: python_script.set_state
          data:
            entity_id: "{{ target_satellite_device }}"
            message: "{{ wiki_response['content']['extract'] }}"
        - set_conversation_response: "{{ wiki_response['content']['extract'] }}"
          enabled: true
        - service: browser_mod.navigate
          data:
            path: /dashboard-viewassist/info
          target:
            device_id: "{{target_display_device}}"
    default:
      - set_conversation_response: Sorry, no entry found
        enabled: true
mode: single
```
